image:
    - Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017

environment:
  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35-x64


# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\Assembly_Metrics_Toolkit

platform: x64

configuration: Release

install:
  - cd c:\projects\Assembly_Metrics_Toolkit
  - cpan App::cpanminus
  - cpanm --installdeps .

build: off

test_script:
  - ps: Start-FileDownload 'https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/agrpla-%28Agrilus_planipennis%29/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Contigs/Aplan.contigs.80.fa.gz'
  - ps: Start-FileDownload 'https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/agrpla-%28Agrilus_planipennis%29/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Scaffolds/Aplan.scaffolds.50.fa.gz'
  - python ./assembly_metrics_toolkit.py -s ./Aplan.scaffolds.50.fa.gz -o example_scaffolds_only.json
  - python ./assembly_metrics_toolkit.py -s ./Aplan.scaffolds.50.fa.gz  -c ./Aplan.contigs.80.fa.gz -o example_scaffolds_and_contigs.json
  - ps: Write-Host "Test scripts are finished ..."

deploy: false