image:
    - Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017

environment:
  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35-x64


# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\Assembly_Metrics_Toolkit

platform: x64

configuration: Release

install:
  - cd c:\projects\Assembly_Metrics_Toolkit
  - cpan App::cpanminus
  - cpanm --installdeps .

build: off

test_script:
  - ps: Start-FileDownload 'https://i5k.nal.usda.gov/data/Arthropoda/athros-(Athalia_rosae)/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Contigs/Aros01112013-contigs.fa.gz'
  - ps: Start-FileDownload 'https://i5k.nal.usda.gov/data/Arthropoda/athros-(Athalia_rosae)/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Scaffolds/Aros01112013-genome.fa.gz'
  - python ./assembly_metrics_toolkit.py -s ./Aros01112013-genome.fa.gz -o example_scaffolds_only.json
  - python ./assembly_metrics_toolkit.py -s ./Aros01112013-genome.fa.gz -c ./Aros01112013-contigs.fa.gz -o example_scaffolds_and_contigs.json
  - ps: Write-Host "Test scripts are finished ..."

deploy: false