sudo: requiered
os: linux
language: python
python:
  - 2.7
  - 3.5
script:
  - curl -L http://cpanmin.us | sudo perl - --self-upgrade
  - sudo cpanm --installdeps .
  - wget "https://i5k.nal.usda.gov/data/Arthropoda/athros-(Athalia_rosae)/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Contigs/Aros01112013-contigs.fa.gz"
  - wget "https://i5k.nal.usda.gov/data/Arthropoda/athros-(Athalia_rosae)/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Scaffolds/Aros01112013-genome.fa.gz"
  - python ./assembly_metrics_toolkit.py -s ./Aros01112013-genome.fa.gz -o example_scaffolds_only.json
  - python ./assembly_metrics_toolkit.py -s ./Aros01112013-genome.fa.gz -c ./Aros01112013-contigs.fa.gz -o example_scaffolds_and_contigs.json