sudo: requiered
os: linux
language: python
python:
  - 2.7
  - 3.5
script:
  - curl -L http://cpanmin.us | sudo perl - --self-upgrade
  - sudo cpanm --installdeps .
  - wget https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/agrpla-%28Agrilus_planipennis%29/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Contigs/Aplan.contigs.80.fa.gz
  - wget https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/agrpla-%28Agrilus_planipennis%29/BCM-After-Atlas/1.Genome%20Assembly/BCM-After-Atlas/Scaffolds/Aplan.scaffolds.50.fa.gz
  - python ./assembly_metrics_toolkit.py -s Aplan.scaffolds.50.fa.gz -o example_scaffolds_only.json
  - python ./assembly_metrics_toolkit.py -s Aplan.scaffolds.50.fa.gz -c ./Aplan.contigs.80.fa.gz -o example_scaffolds_and_contigs.json
